const dictionary = [
    // Verbs and common starts
    [/^Check if /gi, "Verifica se "],
    [/^Initialize /gi, "Inicializa "],
    [/^Close /gi, "Fecha "],
    [/^Toggle /gi, "Alterna "],
    [/^Set /gi, "Define "],
    [/^Clear /gi, "Limpa "],
    [/^Restore /gi, "Restaura "],
    [/^Maximize /gi, "Maximiza "],
    [/^Minimize /gi, "Minimiza "],
    [/^Get /gi, "Obtém "],
    [/^Shows /gi, "Mostra "],
    [/^Hides /gi, "Oculta "],
    [/^Enable /gi, "Habilita "],
    [/^Disable /gi, "Desabilita "],
    [/^Enables /gi, "Habilita "],
    [/^Disables /gi, "Desabilita "],
    [/^Setup /gi, "Configura "],
    [/^Begin /gi, "Inicia "],
    [/^Ends? /gi, "Encerra "],
    [/^Load /gi, "Carrega "],
    [/^Unload /gi, "Descarrega "],
    [/^Wait for /gi, "Espera por "],
    [/^Wait /gi, "Espera "],
    [/^Update /gi, "Atualiza "],
    [/^Draws? /gi, "Desenha "],
    [/^Takes? /gi, "Tira "],
    [/^Open /gi, "Abre "],
    [/^Play /gi, "Toca "],
    [/^Stop /gi, "Para "],
    [/^Pause /gi, "Pausa "],
    [/^Resume /gi, "Retoma "],
    [/^Export /gi, "Exporta "],
    [/^Generate /gi, "Gera "],
    [/^Measure /gi, "Mede "],
    [/^Compute /gi, "Calcula "],
    [/^Upload /gi, "Envia "],
    [/^Copy /gi, "Copia "],
    [/^Crop /gi, "Corta "],
    [/^Convert /gi, "Converte "],
    [/^Modify /gi, "Modifica "],
    [/^Rename /gi, "Renomeia "],
    [/^Remove /gi, "Remove "],
    [/^Move /gi, "Move "],
    [/^Replace /gi, "Substitui "],
    [/^Find /gi, "Encontra "],
    [/^Apply /gi, "Aplica "],
    [/^Seek /gi, "Busca "],
    [/^Attach /gi, "Anexa "],
    [/^Detach /gi, "Desanexa "],
    [/^Encode /gi, "Codifica "],
    [/^Decode /gi, "Decodifica "],
    [/^Compress /gi, "Comprime "],
    [/^Decompress /gi, "Descomprime "],
    [/^Register /gi, "Registra "],
    [/^Create /gi, "Cria "],

    // Specific phrases
    [/window has been initialized successfully/gi, "a janela foi inicializada com sucesso"],
    [/application should close/gi, "o aplicativo deve fechar"],
    [/window is currently fullscreen/gi, "a janela está em tela cheia"],
    [/window is currently hidden/gi, "a janela está oculta"],
    [/window is currently minimized/gi, "a janela está minimizada"],
    [/window is currently maximized/gi, "a janela está maximizada"],
    [/window is currently focused/gi, "a janela está em foco"],
    [/window has been resized last frame/gi, "a janela foi redimensionada no último frame"],
    [/one specific window flag is enabled/gi, "uma flag específica da janela está ativada"],
    [/window configuration state using flags/gi, "o estado de configuração da janela usando flags"],
    [/window configuration state flags/gi, "as flags de estado de configuração da janela"],
    [/window state: fullscreen\/windowed, resizes monitor to match window resolution/gi, "estado da janela: tela cheia/janela, redimensiona o monitor para a resolução da janela"],
    [/window state: borderless windowed, resizes window to match monitor resolution/gi, "estado da janela: sem bordas, redimensiona a janela para a resolução do monitor"],
    [/window state: maximized, if resizable/gi, "estado da janela: maximizada (se redimensionável)"],
    [/window state: minimized, if resizable/gi, "estado da janela: minimizada (se redimensionável)"],
    [/window from being minimized\/maximized/gi, "a janela do estado minimizado/maximizado"],
    [/icon for window/gi, "o ícone da janela"],
    [/title for window/gi, "o título da janela"],
    [/window position on screen/gi, "a posição da janela na tela"],
    [/monitor for the current window/gi, "o monitor da janela atual"],
    [/window minimum dimensions/gi, "as dimensões mínimas da janela"],
    [/window maximum dimensions/gi, "as dimensões máximas da janela"],
    [/window dimensions/gi, "as dimensões da janela"],
    [/window opacity/gi, "a opacidade da janela"],
    [/window focused/gi, "o foco na janela"],
    [/native window handle/gi, "o handle nativo da janela"],
    [/current screen width/gi, "a largura atual da tela"],
    [/current screen height/gi, "a altura atual da tela"],
    [/current render width/gi, "a largura atual de renderização"],
    [/current render height/gi, "a altura atual de renderização"],
    [/number of connected monitors/gi, "o número de monitores conectados"],
    [/current monitor where window is placed/gi, "o monitor atual onde a janela está"],
    [/specified monitor/gi, "o monitor especificado"],
    [/window position XY on monitor/gi, "a posição XY da janela no monitor"],
    [/window scale DPI factor/gi, "o fator de escala DPI da janela"],
    [/clipboard text content/gi, "o conteúdo de texto da área de transferência"],
    [/clipboard image content/gi, "o conteúdo de imagem da área de transferência"],
    [/cursor is not visible/gi, "o cursor não está visível"],
    [/cursor is on the screen/gi, "o cursor está na tela"],
    [/background color/gi, "a cor de fundo"],
    [/canvas drawing and swap buffers/gi, "o desenho e troca os buffers da tela"],
    [/canvas \(framebuffer\) to start drawing/gi, "o canvas (framebuffer) para começar a desenhar"],
    [/drawing to render texture/gi, "o desenho na textura de renderização"],
    [/custom shader drawing/gi, "o desenho com shader customizado"],
    [/blending mode/gi, "o modo de mesclagem"],
    [/scissor mode/gi, "o modo de recorte (scissor)"],
    [/stereo rendering/gi, "a renderização estéreo"],
    [/shader uniform value/gi, "o valor do uniform do shader"],
    [/a ray trace from screen position/gi, "um raio (ray trace) a partir da posição da tela"],
    [/screen space position/gi, "a posição no espaço da tela"],
    [/world space position/gi, "a posição no espaço do mundo"],
    [/camera transform matrix/gi, "a matriz de transformação da câmera"],
    [/camera 2d transform matrix/gi, "a matriz 2D de transformação da câmera"],
    [/target FPS/gi, "o FPS alvo"],
    [/time in seconds for last frame drawn/gi, "o tempo em segundos do último frame"],
    [/elapsed time in seconds/gi, "o tempo decorrido em segundos"],
    [/current FPS/gi, "o FPS atual"],
    [/seed for the random number generator/gi, "a semente do gerador de números aleatórios"],
    [/a random value between min and max/gi, "um valor aleatório entre min e max"],
    [/a screenshot of current screen/gi, "uma captura (screenshot) da tela atual"],
    [/internal memory/gi, "a memória interna"],
    [/file data as byte array/gi, "os dados do arquivo como array de bytes"],
    [/text data from file/gi, "os dados de texto do arquivo"],
    [/data to file from byte array/gi, "os dados no arquivo a partir de um array de bytes"],
    [/text data to file/gi, "os dados de texto no arquivo"],
    [/file extension/gi, "a extensão do arquivo"],
    [/current working directory/gi, "o diretório de trabalho atual"],

    // General Words
    [/\bwindow\b/gi, "janela"],
    [/\bwindows\b/gi, "janelas"],
    [/\bbackground\b/gi, "fundo"],
    [/\bcolor\b/gi, "cor"],
    [/\bcolors\b/gi, "cores"],
    [/\btexture\b/gi, "textura"],
    [/\btextures\b/gi, "texturas"],
    [/\bimage\b/gi, "imagem"],
    [/\bimages\b/gi, "imagens"],
    [/\bsound\b/gi, "som"],
    [/\bsounds\b/gi, "sons"],
    [/\bmusic\b/gi, "música"],
    [/\bfont\b/gi, "fonte"],
    [/\bfonts\b/gi, "fontes"],
    [/\btext\b/gi, "texto"],
    [/\bfile\b/gi, "arquivo"],
    [/\bfiles\b/gi, "arquivos"],
    [/\bdata\b/gi, "dados"],
    [/\bmodel\b/gi, "modelo"],
    [/\bmodels\b/gi, "modelos"],
    [/\bmesh\b/gi, "malha"],
    [/\bmeshes\b/gi, "malhas"],
    [/\bscreen\b/gi, "tela"],
    [/\bmouse\b/gi, "mouse"],
    [/\bkeyboard\b/gi, "teclado"],
    [/\bgamepad\b/gi, "gamepad"],
    [/\bshader\b/gi, "shader"],
    [/\bcamera\b/gi, "câmera"],
    [/\bwidth\b/gi, "largura"],
    [/\bheight\b/gi, "altura"],
    [/\bposition\b/gi, "posição"],
    [/\bdraw\b/gi, "desenhar"],
    [/\bdrawing\b/gi, "desenho"],
    [/\bloaded\b/gi, "carregado"],
    [/\bload\b/gi, "carregar"],
    [/\bsuccessfully\b/gi, "com sucesso"],
    [/\bcurrently\b/gi, "atualmente"],
    [/\band\b/gi, "e"],
    [/\bor\b/gi, "ou"],
    [/\bfor\b/gi, "para"],
    [/\bwith\b/gi, "com"],
    [/\bfrom\b/gi, "de"],
    [/\bto\b/gi, "para"],
    [/\bof\b/gi, "de"],
    [/\bin\b/gi, "em"],
    [/\bis\b/gi, "é/está"],
    [/\bif\b/gi, "se"],
    [/\ban\b/gi, "um/uma"],
    [/\ba\b/gi, "um/uma"],
    [/\bthe\b/gi, "o/a"]
];

function translateText(engDesc) {
    let pt = engDesc;
    for (let i = 0; i < dictionary.length; i++) {
        pt = pt.replace(dictionary[i][0], dictionary[i][1]);
    }
    // Fix casing on first letter
    if (pt.length > 0) {
        pt = pt.charAt(0).toUpperCase() + pt.slice(1);
    }
    return pt;
}

module.exports = { translateText };
